import type { NextPage } from 'next'

import Head from 'next/head'

import styled from 'styled-components';

import { Main, TopBanner, NavBar, Title, PageButton, BottomBanner } from '@Components/index'

const LogoPosition = styled.div`
  width: 100%;
  padding-left: 18px;

  display: flex;
  justify-content: start;

`

const PageButtonPosition = styled.div`
  width: 50%;

  display: flex;
  justify-content: space-around;
`


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <TopBanner>
          <NavBar>
            <LogoPosition>
              <Title>Logo</Title>
            </LogoPosition>
            <PageButtonPosition>
              <PageButton href="https://google.com">PAGE ONE</PageButton>
              <PageButton href="https://google.com">PAGE TWO</PageButton>
              <PageButton href="https://google.com">PAGE THREE</PageButton>
            </PageButtonPosition>
          </NavBar>
        </TopBanner>
        
        <BottomBanner>
        
        </BottomBanner>
      </Main>
    </>
  )
}

export default Home
